name: Test with rspec
on: pull_request

env:
  FORCE_COLOR: 1
  DBUSER: postgres
  DBPASS: postgres
  DBHOST: 127.0.0.1
  RAILS_ENV: test
  S3_BUCKET: plant-xchange-app-dev
  AWS_REGION: us-east-1
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

jobs:
  build:
    runs-on: ubuntu-18.04
    services:
      db:
        image: postgres:11@sha256:85d79cba2d4942dad7c99f84ec389a5b9cc84fb07a3dcd3aff0fb06948cdc03b
        ports: ['5432:5432']
        env:
          DBUSER: postgres
          DBPASS: postgres
          DBHOST: 127.0.0.1
          RAILS_ENV: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.x
      env:
        DBHOST: 127.0.0.1
        DBUSER: postgres
        DBPASS: postgres
        RAILS_ENV: test
    - name: Run Tests
      run: | 
        sudo apt-get -yqq install libpq-dev 
        gem install bundler
        bundle install --jobs 4 --retry 3
        sudo service postgresql restart
        bundle exec rake db:create
        bundle exec rails db:migrate
        bundle exec rspec 